# Generated by Django 5.2.11 on 2026-03-20 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chacara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da chácara para aluguel.",
                        max_length=255,
                        verbose_name="Nome da Chácara",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição detalhada da chácara.",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "preco_diaria",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço da diária de aluguel da chácara.",
                        max_digits=10,
                        verbose_name="Preço da Diária",
                    ),
                ),
                (
                    "tem_estacionamento",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a chácara possui estacionamento.",
                        verbose_name="Tem Estacionamento",
                    ),
                ),
                (
                    "tem_piscina",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a chácara possui piscina.",
                        verbose_name="Tem Piscina",
                    ),
                ),
                (
                    "tem_churrasqueira",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a chácara possui churrasqueira.",
                        verbose_name="Tem Churrasqueira",
                    ),
                ),
                (
                    "num_quartos",
                    models.IntegerField(
                        help_text="Quantidade de quartos disponíveis na chácara.",
                        verbose_name="Número de Quartos",
                    ),
                ),
                (
                    "num_banheiros",
                    models.IntegerField(
                        help_text="Quantidade de banheiros disponíveis na chácara.",
                        verbose_name="Número de Banheiros",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chácara",
                "verbose_name_plural": "Chácaras",
            },
        ),
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do administrador.",
                        max_length=255,
                        verbose_name="Nome Completo",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        help_text="Usuário associado a este administrador.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrador",
                "verbose_name_plural": "Administradores",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do cliente.",
                        max_length=255,
                        verbose_name="Nome Completo",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="Número de telefone do cliente.",
                        max_length=11,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        help_text="Usuário associado a este cliente.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        help_text="Data de início da reserva.",
                        verbose_name="Data de Início",
                    ),
                ),
                (
                    "data_fim",
                    models.DateField(
                        help_text="Data de término da reserva.",
                        verbose_name="Data de Fim",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total da reserva.",
                        max_digits=10,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                            ("CONCLUIDA", "Concluída"),
                        ],
                        default="PENDENTE",
                        help_text="Status atual da reserva.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "chacara",
                    models.ForeignKey(
                        help_text="Chácara reservada.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.chacara",
                        verbose_name="Chácara",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Cliente que realizou a reserva.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
            },
        ),
    ]
