# Generated by Django 5.2.11 on 2026-06-26 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_chacara_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chacara',
            name='num_banheiros',
            field=models.IntegerField(help_text='Quantidade de banheiros disponíveis.', verbose_name='Número de Banheiros'),
        ),
        migrations.AlterField(
            model_name='chacara',
            name='num_quartos',
            field=models.IntegerField(help_text='Quantidade de quartos disponíveis.', verbose_name='Número de Quartos'),
        ),
        migrations.AlterField(
            model_name='chacara',
            name='preco_diaria',
            field=models.DecimalField(decimal_places=2, help_text='Preço por diária em reais.', max_digits=10, verbose_name='Preço da Diária'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(help_text='Número de telefone (somente dígitos).', max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='chacara',
            field=models.ForeignKey(help_text='Chácara que está sendo reservada.', on_delete=django.db.models.deletion.PROTECT, to='website.chacara', verbose_name='Chácara'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente que realizou o pedido de reserva.', on_delete=django.db.models.deletion.PROTECT, to='website.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_fim',
            field=models.DateField(help_text='Data de saída da chácara.', verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_inicio',
            field=models.DateField(help_text='Data de chegada na chácara.', verbose_name='Data de Início'),
        ),
    ]
